name: Deploy Website

on: push

jobs:
  minify-stylesheets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Minify CSS styles
        uses: nizarmah/auto-minify@master
        with:
          directory: "public/css"
        run: |
          cat public/css/main.css

      - name: Verify minified files
        run: |
          cat public/css/main.css
